### PR TITLE
Rewrite run and boot methods, migrate to Fastify

### PR DESCRIPTION
**Pull request by Lenivaya**
# Changes

-   run and boot methods working as expected now
-   instead of express we&rsquo;re using Fastify
-   to fix errors related to es modules support we&rsquo;re using esm package when running node
-   for parsing and stringifying JSON we&rsquo;re now using flatted, which is pretty light and handles circular structures

### CODE REVIEW

**Comment by cureforpain** [comment]
Works as expected with gui

**Comment by ajthinking** [comment]
Great stuff!

> instead of express we’re using Fastify

Any particular reason?

**Review by ajthinking — APPROVED** [review]

**Comment by ajthinking** [comment]
Can you add a custom node here? Just to demo how we can extend the servers capabilites with specialized nodes. In this PR or in follow up. Ill grant you maintainership here in a sec 👍

**Comment by cureforpain** [comment]
> Any particular reason?

- Performance
- Great compatibility provided by Nest.js
- Pretty similar manner of doing things

**Comment by cureforpain** [comment]
> Can you add a custom node here? Just to demo how we can extend the servers capabilites with specialized nodes.

Not a problem, will do that now

**Comment by cureforpain** [comment]
With sample CustomInspectNode added on the server-side all works as expected



related to data-story-org/core#95

**Comment by ajthinking** [comment]
> With sample CustomInspectNode added on the server-side all works as expected

Perfect, looks very smooth!

**Comment by cureforpain** [comment]
With another custom node - bitcoin price fetcher all also works as expected

**Pull request merged**
